services:
  mainstack_backend:
    container_name: mainstack_be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:${PORT}
      - 5000:5000
      # - 5432:5432
    env_file: .env
    environment:
      - PORT=${PORT}